### ISSUE TITLE
Failed to build with RealSense SDK v11 with can't find head files

### ISSUE THREAD

**Issue by wildphoton** [GameTechDev/FaceTracking#1]
I built FaceME in VS2015 with RealSense SDK v11 installed. It reported error that headfiles pxcfacedata.h, pxcfaceconfiguration.h and pxcfacemodule can't be found. I copied those headfiles from [here](https://github.com/libgdx/gdx-realsense/tree/master/native/include), there are still errors reported as followings info:

_1>------ Rebuild All started: Project: FaceME, Configuration: Debug Win32 ------
1>  FMEExprSynthesizer.cpp
1>c:\program files (x86)\intel\rssdk\include\pxcsensemanager.h(20): error C2371: 'PXCFaceModule': redefinition; different basic types
1>  d:\zhenlinxu\code\facetracking\pxcfacemodule.h(15): note: see declaration of 'PXCFaceModule'
1>d:\zhenlinxu\code\facetracking\fmeexprsynthesizer.cpp(125): warning C4018: '<': signed/unsigned mismatch
1>  FMEExprParser.cpp
1>c:\program files (x86)\intel\rssdk\include\pxcsensemanager.h(20): error C2371: 'PXCFaceModule': redefinition; different basic types
1>  d:\zhenlinxu\code\facetracking\pxcfacemodule.h(15): note: see declaration of 'PXCFaceModule'
1>  FMEManager.cpp
1>d:\zhenlinxu\code\facetracking\pxcfacemodule.h(15): error C2371: 'PXCFaceModule': redefinition; different basic types
1>  c:\program files (x86)\intel\rssdk\include\pxcsensemanager.h(20): note: see declaration of 'PXCFaceModule'
1>  FMEFaceTracker.cpp
1>c:\program files (x86)\intel\rssdk\include\pxcsensemanager.h(20): error C2371: 'PXCFaceModule': redefinition; different basic types
1>  d:\zhenlinxu\code\facetracking\pxcfacemodule.h(15): note: see declaration of 'PXCFaceModule'
1>d:\zhenlinxu\code\facetracking\fmefacetracker.cpp(135): error C2440: 'initializing': cannot convert from 'Intel::RealSense::Face::FaceModule *' to 'PXCFaceModule *'
1>  d:\zhenlinxu\code\facetracking\fmefacetracker.cpp(135): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
1>  FMEFace.cpp
1>c:\program files (x86)\intel\rssdk\include\pxcsensemanager.h(20): error C2371: 'PXCFaceModule': redefinition; different basic types
1>  d:\zhenlinxu\code\facetracking\pxcfacemodule.h(15): note: see declaration of 'PXCFaceModule'
1>  FMECommon.cpp
1>  Generating Code...
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========_

Can you help on this? Thanks!

**Comment by CoderGirl42** [comment]
This sample will only work with the 2016 R2 version of the RealSense SDK which is v10.0.26.396. It's the primary download on the realsense SDK website: https://registrationcenter.intel.com/en/products/download/2508/ 

From what I can tell v11 is an "essentials" version, which does not include the necessary headers to compile this sample.
